// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// beam_beam
List beam_beam(List kicked, List kickers, List sim);
RcppExport SEXP _BxB_beam_beam(SEXP kickedSEXP, SEXP kickersSEXP, SEXP simSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type kicked(kickedSEXP);
    Rcpp::traits::input_parameter< List >::type kickers(kickersSEXP);
    Rcpp::traits::input_parameter< List >::type sim(simSEXP);
    rcpp_result_gen = Rcpp::wrap(beam_beam(kicked, kickers, sim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BxB_beam_beam", (DL_FUNC) &_BxB_beam_beam, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_BxB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
