# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name BxB
#'
#' @title B*B, beam-beam simulation for vdM scans at LHC
#'
#' @description "beam_beam" function simulates bunch particles in an
#'              accelerator influenced by the electromagnetic interaction
#'              with another bunch ("beam-beam" effect). Reports corrections
#'              to the bunches overlap integral.
#'
#' @docType package
#' @name BxB
#' @author Vladislav BALAGURA <balagura@cern.ch>
#'
#' @import Rcpp
#' @useDynLib BxB
NULL

#' @title beam_beam
#'
#' @description Simulates bunch particles in an accelerator influenced by the
#'              electromagnetic interaction with another bunch ("beam-beam"
#'              effect). Reports corrections to the bunches overlap integral.
#'
#' @return data.frame summary, including corrections to overlap integrals
#'
#' @author Vladislav BALAGURA <balagura@cern.ch>
#' @export
beam_beam <- function(kicked, kickers, sim) {
    .Call('_BxB_beam_beam', PACKAGE = 'BxB', kicked, kickers, sim)
}

